trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - kubernetes/deployment.yaml

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    displayName: Setup Node.js
    inputs:
      versionSpec: '24.x'

  - script: npm install
    displayName: Install dependencies

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: acridplab-service-connection

  - script: |
      docker run --privileged --rm tonistiigi/binfmt --install arm64
      docker buildx create --use --name idp-builder
      docker buildx inspect --bootstrap
    displayName: Configure ARM64 builder

  - script: |
      docker buildx build \
        --platform linux/arm64 \
        --push \
        -t acridplab.azurecr.io/${{ values.repoName }}:$(Build.SourceVersion) \
        .
    displayName: Build and push image
  
  - script: |
      sed -i "s|image: acridplab.azurecr.io/${{ values.repoName }}:.*|image: acridplab.azurecr.io/${{ values.repoName }}:$(Build.SourceVersion)|" kubernetes/deployment.yaml

      git config user.name "Azure Pipelines"
      git config user.email "azure-pipelines@wh4sistemas.local"

      git add kubernetes/deployment.yaml

      if git diff --cached --quiet; then
        echo "Nenhuma alteração no manifesto."
        exit 0
      fi

      git commit -m "chore: update image to $(Build.SourceVersion)"
      git push origin HEAD:main
    displayName: Update Kubernetes manifest  