apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: ${{ values.dbName }}-db
  namespace: database
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: azure