{% if values.createPostgres %}
apiVersion: platform.idp.local/v1alpha1
kind: PostgreSQLInstance

metadata:
  name: '${{ values.repoName }}-db'
  namespace: '${{ values.repoName }}'
  labels:
    backstage.io/kubernetes-id: '${{ values.repoName }}'

spec:
  parameters:
    size: '${{ values.databaseSize }}'
    storageGB: ${{ values.databaseStorageGB }}
    version: '${{ values.databaseVersion }}'
    databaseName: '${{ values.databaseName }}'
{% else %}
# PostgreSQL não solicitado para esta aplicação.
{% endif %}