apiVersion: v1
kind: Service

metadata:
  name: '${{ values.repoName }}'
  labels:
    app: '${{ values.repoName }}'
    backstage.io/kubernetes-id: '${{ values.repoName }}'

spec:
  type: ClusterIP

  selector:
    app: '${{ values.repoName }}'

  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP